---
new_page_extension: md
auto_deploy: false
admin_path: "/static/edit"
webhook_url: 
sections:
- type: directory
  path: src/content/work
  label: Work
  create: documents
  match: "**/*"
  templates:
  - work
- type: directory
  path: src/content/press
  label: Press
  create: documents
  match: "**/*"
  templates:
  - press
- type: document
  path: src/content/story.md
  label: Story
- type: document
  path: src/content/contact.md
  label: Contact & Social
upload_dir: static/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run develop-hosted
